
import React from "react";
import Head from "next/head";
import { Layout } from "antd";
import HeaderComponents from "../ui/common/Header/components/Header";
import SiderComponents from "../ui/common/Sider/Sider";
import Main from "../ui/common/Main/Main";
import FooterComponent from "../ui/common/Footer/Footer";

const { Header, Content, Footer, Sider } = Layout;

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function AdminLayout({ children }) {
  return (
    <html lang="en">
      <Head>
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin />
        <link
          href="https://fonts.googleapis.com/css2?family=Roboto:wght@300;400;500;700&display=swap"
          rel="stylesheet"
        />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
        <link
          href="https://fonts.googleapis.com/css2?family=Raleway:wght@500&display=swap"
          rel="stylesheet"
        />
      </Head>
      <body>
        
        {/* <Layout hasSider> */}
         
         <SiderComponents />
         <Layout
           style={{
             marginLeft: 200,
           }}>
           <HeaderComponents />
           <Main>
             {children}
           </Main>
           <FooterComponent/>
         </Layout>
       {/* </Layout> */}
        
        
      </body>
    </html>
  );
}
