import Header from "./ui/Header"
import Sidebar from "./ui/Sidebar"
import './globals.css'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className=" font-['Roboto'] grid grid-cols-[0.5fr,1fr,1fr,1fr,1fr] grid-rows-[1fr,3fr,3fr,3fr,3fr,3fr]  ">
         <Sidebar/>
         <Header/>  
        {children}
      </body>
    </html>
  )
}
